//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.21 at 01:16:10 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:posten.no/ec", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mqconsumer.demo.schema;
